[build]
builder = "DOCKERFILE"
dockerfilePath = "../Dockerfile"  # Path to the Dockerfile in the root

[deploy]
numReplicas = 1
healthcheckPath = "/docs"  # Health check path for your FastAPI app
healthcheckTimeout = 120   # Timeout in seconds
restartPolicyType = "always"